// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(full-width-pages)/(auth)/signin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signin">> = Specific
  const handler = {} as typeof import("../../src/app/(full-width-pages)/(auth)/signin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(full-width-pages)/(auth)/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../src/app/(full-width-pages)/(auth)/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(full-width-pages)/(auth)/two-step-verification/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/two-step-verification">> = Specific
  const handler = {} as typeof import("../../src/app/(full-width-pages)/(auth)/two-step-verification/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(full-width-pages)/(error-pages)/error-404/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/error-404">> = Specific
  const handler = {} as typeof import("../../src/app/(full-width-pages)/(error-pages)/error-404/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(full-width-pages)/(error-pages)/error-500/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/error-500">> = Specific
  const handler = {} as typeof import("../../src/app/(full-width-pages)/(error-pages)/error-500/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(full-width-pages)/(error-pages)/error-503/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/error-503">> = Specific
  const handler = {} as typeof import("../../src/app/(full-width-pages)/(error-pages)/error-503/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(full-width-pages)/(error-pages)/maintenance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance">> = Specific
  const handler = {} as typeof import("../../src/app/(full-width-pages)/(error-pages)/maintenance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(full-width-pages)/coming-soon/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/coming-soon">> = Specific
  const handler = {} as typeof import("../../src/app/(full-width-pages)/coming-soon/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(full-width-pages)/success/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/success">> = Specific
  const handler = {} as typeof import("../../src/app/(full-width-pages)/success/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/admin/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/analytics/revenue/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/analytics/revenue">> = Specific
  const handler = {} as typeof import("../../src/app/admin/analytics/revenue/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/api-keys/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/api-keys/create">> = Specific
  const handler = {} as typeof import("../../src/app/admin/api-keys/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/api-keys/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/api-keys">> = Specific
  const handler = {} as typeof import("../../src/app/admin/api-keys/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/health/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/health">> = Specific
  const handler = {} as typeof import("../../src/app/admin/health/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../src/app/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/users/invite/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users/invite">> = Specific
  const handler = {} as typeof import("../../src/app/admin/users/invite/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api-docs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/api-docs">> = Specific
  const handler = {} as typeof import("../../src/app/api-docs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api-management/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/api-management">> = Specific
  const handler = {} as typeof import("../../src/app/api-management/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/auth-code-error/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/auth-code-error">> = Specific
  const handler = {} as typeof import("../../src/app/auth/auth-code-error/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/auth/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/auth/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/signin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/signin">> = Specific
  const handler = {} as typeof import("../../src/app/auth/signin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/profile">> = Specific
  const handler = {} as typeof import("../../src/app/settings/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tenant-management/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tenant-management/create">> = Specific
  const handler = {} as typeof import("../../src/app/tenant-management/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tenant-management/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tenant-management">> = Specific
  const handler = {} as typeof import("../../src/app/tenant-management/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/test-auth-fix/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-auth-fix">> = Specific
  const handler = {} as typeof import("../../src/app/test-auth-fix/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/test-magic-link/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-magic-link">> = Specific
  const handler = {} as typeof import("../../src/app/test-magic-link/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/test-signin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-signin">> = Specific
  const handler = {} as typeof import("../../src/app/test-signin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/test-tenant-creation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-tenant-creation">> = Specific
  const handler = {} as typeof import("../../src/app/test-tenant-creation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/test/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test">> = Specific
  const handler = {} as typeof import("../../src/app/test/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/api-keys/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/api-keys/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/api-keys/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/api-keys/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/api-keys">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/api-keys/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/assignments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/assignments">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/assignments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/platform-apis/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/platform-apis">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/platform-apis/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/providers/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/providers/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/providers/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/providers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/providers">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/providers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/reset-user-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reset-user-password">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/reset-user-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/services/blog-writer/config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/services/blog-writer/config">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/services/blog-writer/config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/services/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/services">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/services/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/tenants/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/tenants">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/tenants/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/users/demote/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/demote">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/users/demote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/users/promote-tenant-admin/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/promote-tenant-admin">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/users/promote-tenant-admin/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/users/promote/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/promote">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/users/promote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/process/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/process">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/process/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/signout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/signout">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/signout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/blog-writer/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/blog-writer/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/blog-writer/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/blog-writer/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/blog-writer/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/blog-writer/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/debug/check-db/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug/check-db">> = Specific
  const handler = {} as typeof import("../../src/app/api/debug/check-db/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/debug/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug/session">> = Specific
  const handler = {} as typeof import("../../src/app/api/debug/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/debug/tenant-admin/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug/tenant-admin">> = Specific
  const handler = {} as typeof import("../../src/app/api/debug/tenant-admin/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/deployment-test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/deployment-test">> = Specific
  const handler = {} as typeof import("../../src/app/api/deployment-test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/health-check/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health-check">> = Specific
  const handler = {} as typeof import("../../src/app/api/health-check/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/keys/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/keys/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/keys/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/keys/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/keys">> = Specific
  const handler = {} as typeof import("../../src/app/api/keys/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/keys/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/keys/stats">> = Specific
  const handler = {} as typeof import("../../src/app/api/keys/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/setup/tenant-admin/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/setup/tenant-admin">> = Specific
  const handler = {} as typeof import("../../src/app/api/setup/tenant-admin/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tenant/api-keys/[keyId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tenant/api-keys/[keyId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/tenant/api-keys/[keyId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tenant/api-keys/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tenant/api-keys">> = Specific
  const handler = {} as typeof import("../../src/app/api/tenant/api-keys/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tenant/billing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tenant/billing">> = Specific
  const handler = {} as typeof import("../../src/app/api/tenant/billing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tenant/invite/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tenant/invite">> = Specific
  const handler = {} as typeof import("../../src/app/api/tenant/invite/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tenant/log-usage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tenant/log-usage">> = Specific
  const handler = {} as typeof import("../../src/app/api/tenant/log-usage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tenant/menu/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tenant/menu">> = Specific
  const handler = {} as typeof import("../../src/app/api/tenant/menu/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tenant/provisioning-keys/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tenant/provisioning-keys">> = Specific
  const handler = {} as typeof import("../../src/app/api/tenant/provisioning-keys/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tenant/roles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tenant/roles">> = Specific
  const handler = {} as typeof import("../../src/app/api/tenant/roles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tenant/statistics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tenant/statistics">> = Specific
  const handler = {} as typeof import("../../src/app/api/tenant/statistics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tenant/usage-analytics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tenant/usage-analytics">> = Specific
  const handler = {} as typeof import("../../src/app/api/tenant/usage-analytics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tenant/users/[userId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tenant/users/[userId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/tenant/users/[userId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/test-auth-callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/test-auth-callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/test-auth-callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/test-auth-fix/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/test-auth-fix">> = Specific
  const handler = {} as typeof import("../../src/app/api/test-auth-fix/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/test-magic-link/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/test-magic-link">> = Specific
  const handler = {} as typeof import("../../src/app/api/test-magic-link/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/test-simple/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/test-simple">> = Specific
  const handler = {} as typeof import("../../src/app/api/test-simple/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/test-tenant-roles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/test-tenant-roles">> = Specific
  const handler = {} as typeof import("../../src/app/api/test-tenant-roles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/ai/process/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/ai/process">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/ai/process/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/blog-writer/analyze/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/blog-writer/analyze">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/blog-writer/analyze/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/blog-writer/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/blog-writer/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/blog-writer/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/blog-writer/keywords/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/blog-writer/keywords">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/blog-writer/keywords/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../src/app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(full-width-pages)/(auth)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(full-width-pages)/(auth)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(full-width-pages)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(full-width-pages)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
